# Default recipe - list available commands
[private]
default:
    @just --list

# Create new note (usage: just new "my-note-title")
[working-directory: '../..']
new title:
    hugo new notes/{{title}}.md
